{{- if .Values.rbac.clusterScope.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rafter.rbacClusterRoleBindingName" . }}
  labels:
    app.kubernetes.io/name: {{ include "rafter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "rafter.chart" . }}
  {{- if .Values.rbac.clusterScope.roleBinding.labels }}
    {{ toYaml .Values.rbac.clusterScope.roleBinding.labels | indent 4 }}
  {{- end }}
  {{- if .Values.rbac.clusterScope.roleBinding.annotations }}
  annotations:
    {{ toYaml .Values.rbac.clusterScope.roleBinding.annotations | indent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rafter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rafter.rbacClusterRoleName" . }}
{{- end }}