// Code generated by failery v1.0.0. DO NOT EDIT.

package disabled

import v1alpha1 "github.com/kyma-project/kyma/components/cms-controller-manager/pkg/apis/cms/v1alpha1"

// clusterDocsTopicGetter is an autogenerated failing mock type for the clusterDocsTopicGetter type
type clusterDocsTopicGetter struct {
	err error
}

// NewClusterDocsTopicGetter creates a new clusterDocsTopicGetter type instance
func NewClusterDocsTopicGetter(err error) *clusterDocsTopicGetter {
	return &clusterDocsTopicGetter{err: err}
}

// List provides a failing mock function with given fields: groupName
func (_m *clusterDocsTopicGetter) List(groupName string) ([]*v1alpha1.ClusterDocsTopic, error) {
	var r0 []*v1alpha1.ClusterDocsTopic
	var r1 error
	r1 = _m.err

	return r0, r1
}
