// Code generated by mockery v1.0.0. DO NOT EDIT.
package automock

import mock "github.com/stretchr/testify/mock"
import v1alpha1 "github.com/kyma-project/kyma/components/cms-controller-manager/pkg/apis/cms/v1alpha1"

// clusterDocsTopicGetter is an autogenerated mock type for the clusterDocsTopicGetter type
type clusterDocsTopicGetter struct {
	mock.Mock
}

// List provides a mock function with given fields: groupName
func (_m *clusterDocsTopicGetter) List(groupName string) ([]*v1alpha1.ClusterDocsTopic, error) {
	ret := _m.Called(groupName)

	var r0 []*v1alpha1.ClusterDocsTopic
	if rf, ok := ret.Get(0).(func(string) []*v1alpha1.ClusterDocsTopic); ok {
		r0 = rf(groupName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1alpha1.ClusterDocsTopic)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(groupName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
