---
# Source: serverless/templates/backendmodule.yaml
apiVersion: ui.kyma-project.io/v1alpha1
kind: BackendModule
metadata:
  name: serverless
  labels:
    app: 'serverless'
    app.kubernetes.io/instance: 'RELEASE-NAME'
    app.kubernetes.io/managed-by: 'Helm'
    app.kubernetes.io/name: 'serverless'
    app.kubernetes.io/version: 'f4e7f64c'
    helm.sh/chart: 'serverless-1.0.0'
    version: 'f4e7f64c'
