---
# Source: serverless/templates/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: serverless
  labels:
    app: 'serverless'
    app.kubernetes.io/instance: 'RELEASE-NAME'
    app.kubernetes.io/managed-by: 'Helm'
    app.kubernetes.io/name: 'serverless'
    app.kubernetes.io/version: 'f4e7f64c'
    helm.sh/chart: 'serverless-1.0.0'
    version: 'f4e7f64c'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: serverless
subjects:
- kind: ServiceAccount
  name: serverless-controller-manager
  namespace: default
