---
# Source: serverless/templates/cluster-microfrontend-functions.yaml
apiVersion: "ui.kyma-project.io/v1alpha1"
kind: ClusterMicroFrontend
metadata:
  name: serverless
  labels:
    app: 'serverless'
    app.kubernetes.io/instance: 'RELEASE-NAME'
    app.kubernetes.io/managed-by: 'Helm'
    app.kubernetes.io/name: 'serverless'
    app.kubernetes.io/version: 'f4e7f64c'
    helm.sh/chart: 'serverless-1.0.0'
    version: 'f4e7f64c'
spec:
  displayName: Functions
  version: v1
  category: Development
  placement: namespace
  viewBaseUrl: 'https://core-ui.\x3Cno value\x3E'
  navigationNodes:
    - label: Functions
      navigationPath: functions
      viewUrl: '/lambdas'
      order: 1
      viewGroup: "_core_ui_"
      requiredBackendModules:
        - serverless
    - label: Functions
      navigationPath: functions/details
      viewUrl: '/lambdas'
      showInNavigation: false
      viewGroup: "_core_ui_"
    - label: Function Details
      navigationPath: functions/details/:lambda
      viewUrl: '/lambda/:lambda'
      showInNavigation: false
      viewGroup: "_core_ui_"
