---
# Source: serverless/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverless-ctrl-mngr
  namespace: default
  labels:
    app: 'serverless'
    app.kubernetes.io/instance: 'RELEASE-NAME'
    app.kubernetes.io/managed-by: 'Helm'
    app.kubernetes.io/name: 'serverless'
    app.kubernetes.io/version: 'f4e7f64c'
    helm.sh/chart: 'serverless-1.0.0'
    version: 'f4e7f64c'
spec:
  selector:
    matchLabels:
      app: serverless
      app.kubernetes.io/name: serverless
      app.kubernetes.io/instance: "RELEASE-NAME"
  replicas: 1
  template:
    metadata:
      labels:
        app: serverless
        app.kubernetes.io/name: serverless
        app.kubernetes.io/instance: "RELEASE-NAME"
      annotations:
        
        sidecar.istio.io/inject: "false"
        
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: serverless-controller-manager
      
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: "eu.gcr.io/kyma-project/function-controller:f4e7f64c"
          imagePullPolicy: IfNotPresent
          command:
          - /app/manager
          resources:
            limits:
              cpu: 100m
              memory: 126Mi
            requests:
              cpu: 10m
              memory: 32Mi
          ports:
            - containerPort: 8080
              name: http-metrics
              protocol: TCP
          env:
            - name: APP_METRICS_ADDRESS
              value: ":8080"
            - name: APP_FUNCTION_DOCKER_INTERNAL_REGISTRY_ENABLED
              value: "true"
            - name: APP_FUNCTION_DOCKER_INTERNAL_SERVER_ADDRESS
              value: "serverless-docker-registry.default.svc.cluster.local:5000"
            - name: APP_FUNCTION_DOCKER_REGISTRY_ADDRESS
              value: "registry."
            
            - name: APP_KUBERNETES_CONFIG_MAP_REQUEUE_DURATION
              value: 5m
            
            - name: APP_KUBERNETES_SECRET_REQUEUE_DURATION
              value: 5m
            
            - name: APP_KUBERNETES_SERVICE_ACCOUNT_REQUEUE_DURATION
              value: 5m
            
            - name: APP_KSERVICE_REQUEUE_DURATION
              value: 5m
            
            - name: APP_KUBERNETES_EXCLUDED_NAMESPACES
              value: istio-system,knative-eventing,knative-serving,kube-node-lease,kube-public,kube-system,kyma-installer,kyma-integration,kyma-system,natss,compass-system
            
            - name: APP_FUNCTION_IMAGE_REGISTRY_DOCKER_CONFIG_SECRET_NAME
              value: 'serverless-image-pull-secret'
            
            - name: APP_FUNCTION_IMAGE_PULL_ACCOUNT_NAME
              value: 'serverless'
            
            - name: APP_FUNCTION_REQUEUE_DURATION
              value: 5m
            
            - name: APP_FUNCTION_BUILD_EXECUTOR_ARGS
              value: --insecure,--skip-tls-verify,--skip-unused-stages,--log-format=text,--cache=true
            
            - name: APP_FUNCTION_BUILD_EXECUTOR_IMAGE
              value: gcr.io/kaniko-project/executor:v0.22.0
            
            - name: APP_FUNCTION_TARGET_CPU_UTILIZATION_PERCENTAGE
              value: "50"
            
            - name: APP_FUNCTION_BUILD_REPOFETCHER_IMAGE
              value: eu.gcr.io/kyma-project/function-build-init:1088c1af
