{
 "title": "Kyma / Function",
 "tags": [ "kyma" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_service_labels{label_serverless_kyma_project_io_function_name=~\".+\"},namespace)"
   },
   {
    "name": "function_name",
    "label": "Function",
    "query": "label_values(kube_service_labels{label_serverless_kyma_project_io_function_name=~\".+\",namespace=\"$namespace\"},service)"
   },
   { "name": "function_container", "query": "lambda" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ratio of Requests per Response Codes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_namespace=\"$namespace\", destination_service_name=\"$function_name\",response_code=~\"2.*\"}[2m])) by (destination_service_name) / sum(rate(istio_requests_total{destination_service_namespace=\"$namespace\", destination_service_name=\"$function_name\",}[2m])) by (destination_service_name)",
     "legendFormat": "2xx response code"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_namespace=\"$namespace\", destination_service_name=\"$function_name\",response_code=~\"5.*\"}[2m])) by (destination_service_name) / sum(rate(istio_requests_total{destination_service_namespace=\"$namespace\", destination_service_name=\"$function_name\"}[2m])) by (destination_service_name)",
     "legendFormat": "5xx response code"
    },
    {
     "expr": "sum(rate(istio_requests_total{destination_service_namespace=\"$namespace\", destination_service_name=\"$function_name\",response_code=~\"4.*\"}[2m])) by (destination_service_name) / sum(rate(istio_requests_total{destination_service_namespace=\"$namespace\", destination_service_name=\"$function_name\"}[2m])) by (destination_service_name)",
     "legendFormat": "4xx response code"
    }
   ]
  },
  {
   "title": "Request Duration (95th)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_seconds_bucket{destination_service_namespace=\"$namespace\", destination_service_name=\"$function_name\"}[2m])) by (destination_service_name, le))",
     "legendFormat": "Request Duration"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(max(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"$function_name.*\", pod!~\"$function_name-build.*\", container=\"$function_container\"}) / max (kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$function_name.*\", pod!~\"$function_name-build.*\", container=\"$function_container\"})) * 100",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max (rate(container_cpu_usage_seconds_total{container=\"$function_container\", pod=~\"$function_name.*\", pod!~\"$function_name-build.*\", namespace=\"$namespace\"}[2m])  )",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Success Rate (Ratio of 2xx Responses)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_namespace=\"$namespace\", destination_service_name=\"$function_name\", response_code=~\"2.*\"}[2m])) / sum(rate(istio_requests_total{destination_service_namespace=\"$namespace\", destination_service_name=\"$function_name\"}[2m])) "
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=~\"$function_name-.*\",namespace=\"$namespace\"}",
     "legendFormat": "Replicas"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Requests per Second by Response Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_namespace=\"$namespace\", destination_service_name=\"$function_name\"}[2m])) by (destination_service, response_code)",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "Response Time per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(istio_request_duration_seconds_bucket{destination_service_namespace=\"$namespace\", destination_service_name=\"$function_name\"}[2m])) by (destination_service_name, le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(istio_request_duration_seconds_bucket{destination_service_namespace=\"$namespace\", destination_service_name=\"$function_name\"}[2m])) by (destination_service_name, le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_seconds_bucket{destination_service_namespace=\"$namespace\", destination_service_name=\"$function_name\"}[2m])) by (destination_service_name, le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_seconds_bucket{destination_service_namespace=\"$namespace\", destination_service_name=\"$function_name\"}[2m])) by (destination_service_name, le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"$function_name.*\", pod!~\"$function_name-build.*\", container=\"$function_container\"})",
     "legendFormat": "Current {{pod}}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=~\"$function_name.*\", pod!~\"$function_name-build.*\", container=\"$function_container\"})",
     "legendFormat": "Limit {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"$function_container\", pod=~\"$function_name.*\", pod!~\"$function_name-build.*\", namespace=\"$namespace\"}[2m])",
     "legendFormat": "Current {{pod}}"
    },
    {
     "expr": "sum by(pod) (kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$function_name.*\", pod!~\"$function_name-build.*\", container=\"$function_container\"})",
     "legendFormat": "Limit {{pod}}"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_hpa_status_current_replicas{hpa=~\"$function_name-.*\",namespace=\"$namespace\"}",
     "legendFormat": "Replicas"
    },
    {
     "expr": "kube_hpa_spec_max_replicas{hpa=~\"$function_name-.*\",namespace=\"$namespace\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "kube_hpa_spec_min_replicas{hpa=~\"$function_name-.*\",namespace=\"$namespace\"}",
     "legendFormat": "Min"
    }
   ]
  }
 ]
}