---
# Source: serverless/templates/function-usage-kind.yaml
apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: UsageKind
metadata:
  name: "serverless-function"
spec:
  displayName: Function
  resource:
    group: serverless.kyma-project.io
    kind: function
    version: v1alpha1
  labelsPath: spec.labels
