---
# Source: serverless/templates/runtimes.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dockerfile-nodejs-12
  namespace: default
  labels:
    serverless.kyma-project.io/config: runtime
    serverless.kyma-project.io/runtime: nodejs12
data:
  Dockerfile: |-
    FROM eu.gcr.io/kyma-project/function-runtime-nodejs12:2bba165a
    USER root
    ENV KUBELESS_INSTALL_VOLUME=/kubeless
    
    COPY /src/package.json $KUBELESS_INSTALL_VOLUME/package.json
    RUN /kubeless-npm-install.sh
    COPY /src $KUBELESS_INSTALL_VOLUME

    USER 1000
---
# Source: serverless/templates/runtimes.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dockerfile-nodejs-10
  namespace: default
  labels:
    serverless.kyma-project.io/config: runtime
    serverless.kyma-project.io/runtime: nodejs10
data:
  Dockerfile: |-
    FROM eu.gcr.io/kyma-project/function-runtime-nodejs10:2bba165a
    USER root
    ENV KUBELESS_INSTALL_VOLUME=/kubeless
    
    COPY /src/package.json $KUBELESS_INSTALL_VOLUME/package.json
    RUN /kubeless-npm-install.sh
    COPY /src $KUBELESS_INSTALL_VOLUME

    USER 1000
---
# Source: serverless/templates/runtimes.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dockerfile-python-38
  namespace: default
  labels:
    serverless.kyma-project.io/config: runtime
    serverless.kyma-project.io/runtime: python38
data:
  Dockerfile: |-
    FROM eu.gcr.io/kyma-project/function-runtime-python38:2bba165a
    USER root
    ENV KUBELESS_INSTALL_VOLUME=/kubeless
    
    COPY /src/requirements.txt $KUBELESS_INSTALL_VOLUME/requirements.txt
    RUN pip install -r $KUBELESS_INSTALL_VOLUME/requirements.txt
    COPY /src $KUBELESS_INSTALL_VOLUME

    USER 1000
