---
# Source: serverless/templates/service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: 'serverless'
    app.kubernetes.io/instance: 'RELEASE-NAME'
    app.kubernetes.io/managed-by: 'Helm'
    app.kubernetes.io/name: 'serverless'
    app.kubernetes.io/version: 'f4e7f64c'
    helm.sh/chart: 'serverless-1.0.0'
    version: 'f4e7f64c'
  name: serverless
  namespace: default
spec:
  endpoints:
    - path: /metrics
      port: http-metrics
      interval: "30s"
  selector:
    matchLabels:
      app: serverless
      app.kubernetes.io/name: serverless
      app.kubernetes.io/instance: "RELEASE-NAME"
