# Default values for webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride:
fullnameOverride:
image:
  repository: "eu.gcr.io/kyma-project/function-webhook"
  tag: "b04bc441"
  pullPolicy: IfNotPresent

commonLabels:
  app: '{{ template "webhook.fullname" . }}'
  app.kubernetes.io/name: '{{ template "webhook.fullname" . }}'
  app.kubernetes.io/instance: "{{ .Release.Name }}"
  app.kubernetes.io/managed-by: "{{ .Release.Service }}"
  role: webhook

deployment:
  replicas: 1
  labels: {}
  annotations: {}
  extraProperties: {}

pod:
  annotations:
    sidecar.istio.io/inject: "false"
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

service:
  ports:
    httpMetrics:
      name: "http-metrics"
      port: 9090
      targetPort: 9090
    httpProfiling:
      name: "http-profiling"
      port: 8008
      targetPort: 8008
    httpsWebhook:
      name: "https-webhook"
      port: 443
      targetPort: 8443

container:
  allowPrivilegeEscalation: false
  envs:
    metricsDomain:
      value: "kyma-project.io/serverless"
    configObservabilityName:
      value: '{{ template "webhook.fullname" . }}-config-observability'
    webhookServiceName:
      value: '{{ template "webhook.fullname" . }}'
    webhookSecretName:
      value: '{{ template "webhook.fullname" . }}'
    webhookPort:
      value: "{{ .Values.service.ports.httpsWebhook.targetPort }}"
    reservedEnvs:
      value: "FUNC_RUNTIME,FUNC_HANDLER,FUNC_PORT,MOD_NAME,NODE_PATH,PYTHONPATH" # https://github.com/kubeless/runtimes/blob/master/stable/nodejs/kubeless.js;https://github.com/kubeless/runtimes/tree/master/stable/python
    function:
      replicas:
        minValue: "1"
        defaultPreset: "s"
        presets: |-
          {
            "s": {
              "min": 1,
              "max": 1
            },
            "m": {
              "min": 1,
              "max": 2
            },
            "l": {
              "min": 1,
              "max": 5
            }
          }
      resources:
        minRequestCpu: "10m"
        minRequestMemory: "16Mi"
        defaultPreset: "m"
        presets: |-
          {
            "xs": {
              "requestCpu": "10m",
              "requestMemory": "16Mi",
              "limitCpu": "25m",
              "limitMemory": "32Mi"
            },
            "s": {
              "requestCpu": "25m",
              "requestMemory": "32Mi",
              "limitCpu": "50m",
              "limitMemory": "64Mi"
            },
            "m": {
              "requestCpu": "50m",
              "requestMemory": "64Mi",
              "limitCpu": "100m",
              "limitMemory": "128Mi"
            },
            "l": {
              "requestCpu": "100m",
              "requestMemory": "128Mi",
              "limitCpu": "200m",
              "limitMemory": "256Mi"
            },
            "xl": {
              "requestCpu": "200m",
              "requestMemory": "256Mi",
              "limitCpu": "400m",
              "limitMemory": "512Mi"
            }
          }
    buildJob:
      resources:
        minRequestCpu: "200m"
        minRequestMemory: "200Mi"
        defaultPreset: "normal"
        presets: |-
          {
            "slow": {
              "requestCpu": "200m",
              "requestMemory": "200Mi",
              "limitCpu": "700m",
              "limitMemory": "700Mi"
            },
            "normal": {
              "requestCpu": "700m",
              "requestMemory": "700Mi",
              "limitCpu": "1100m",
              "limitMemory": "1100Mi"
            },
            "fast": {
              "requestCpu": "1100m",
              "requestMemory": "1100Mi",
              "limitCpu": "1700m",
              "limitMemory": "1700Mi"
            }
          }
