# Default values for rafter-asyncapi-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride:
fullnameOverride:

image:
  repository: eu.gcr.io/kyma-project/pr/rafter-asyncapi-service
  tag: PR-15
  pullPolicy: IfNotPresent

deployment:
  labels: {}
  annotations: {}
  replicas: 1
  extraProperties: {}

pod:
  labels: {}
  annotations: {}
  extraProperties: {}
  extraContainerProperties: {}

service:
  name:
  type: ClusterIP
  port:
    name: http
    internal: 3000
    external: 80
    protocol: TCP
  labels: {}
  annotations: {}

serviceMonitor:
  create: false
  name:
  scrapeInterval: 30s
  labels: {}
  annotations: {}

envs:
  host:
    value: "0.0.0.0"
  verbose: 
    value: "true"