dependencies:
  - name: minio
    condition: minio.enabled
  - name: controller-manager
    condition: controller-manager.enabled
  - name: upload-service
    condition: upload-service.enabled
  - name: frontmatter-service
    condition: frontmatter-service.enabled
  - name: asyncapi-service
    condition: asyncapi-service.enabled