apiVersion: v1
version: 0.1.0
appVersion: 0.1.0
name: rafter-upload-service
description: A Helm chart for Upload Service
home: https://github.com/kyma-project/rafter
sources:
  - https://github.com/kyma-project/rafter
keywords:
  - rafter
  - storage
  - assets
  - buckets
  - assetgroups
  - upload
  - webhook
  - minio
maintainers:
  - name: derberg
    email: "lukasz.gornicki.83@gmail.com"
  - name: michal-hudy
    email: "michal@hudy.pl"
  - name: m00g3n
    email: "marcin.witalis@gmail.com"
  - name: aerfio
    email: "mati6095@gmail.com"
  - name: magicmatatjahu
    email: "urbanczyk.maciej.95@gmail.com"
