// Code generated by failery v1.0.0. DO NOT EDIT.

package disabled

import v1alpha2 "github.com/kyma-project/kyma/components/asset-store-controller-manager/pkg/apis/assetstore/v1alpha2"

// assetGetter is an autogenerated failing mock type for the assetGetter type
type assetGetter struct {
	err error
}

// NewAssetGetter creates a new assetGetter type instance
func NewAssetGetter(err error) *assetGetter {
	return &assetGetter{err: err}
}

// List provides a failing mock function with given fields: namespace, groupName
func (_m *assetGetter) List(namespace string, groupName string) ([]*v1alpha2.Asset, error) {
	var r0 []*v1alpha2.Asset
	var r1 error
	r1 = _m.err

	return r0, r1
}
