// Code generated by failery v1.0.0. DO NOT EDIT.

package disabled

import v1alpha2 "github.com/kyma-project/kyma/components/asset-store-controller-manager/pkg/apis/assetstore/v1alpha2"

// assetSvc is an autogenerated failing mock type for the assetSvc type
type assetSvc struct {
	err error
}

// NewAssetSvc creates a new assetSvc type instance
func NewAssetSvc(err error) *assetSvc {
	return &assetSvc{err: err}
}

// List provides a failing mock function with given fields: namespace, groupName
func (_m *assetSvc) List(namespace string, groupName string) ([]*v1alpha2.Asset, error) {
	var r0 []*v1alpha2.Asset
	var r1 error
	r1 = _m.err

	return r0, r1
}

// ListForDocsTopicByType provides a failing mock function with given fields: namespace, docsTopicName, typeArg
func (_m *assetSvc) ListForDocsTopicByType(namespace string, docsTopicName string, typeArg *string) ([]*v1alpha2.Asset, error) {
	var r0 []*v1alpha2.Asset
	var r1 error
	r1 = _m.err

	return r0, r1
}
