# Default values for rafter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride:
fullnameOverride:

image:
  repository:
  tag:
  pullPolicy:

installCRDs: true

deployment:
  labels: {}
  annotations: {}
  replicas: 1
  extraProperties: {}

pod:
  labels: {}
  annotations: {}
  resources: {}
  volumes: []
  volumeMounts: []
  extraProperties: {}
  extraContainerProperties: {}

serviceAccount:
  create: true
  name:
  labels: {}
  annotations: {}

rbac:
  clusterScope:
    create: true
    role:
      name:
      labels: {}
      annotations: {}
      extraRules: []
    roleBinding:
      name:
      labels: {}
      annotations: {}
  namespaced:
    create: true
    role:
      name:
      labels: {}
      annotations: {}
      extraRules: []
    roleBinding:
      name:
      labels: {}
      annotations: {}

webhooksConfigMap:
  create: true
  name:
  namespace: "{{ .Release.Namespace }}"
  hooks: {}
  labels: {}
  annotations: {}

metrics:
  enabled: true
  service:
    name:
    type: ClusterIP
    port:
      name: metrics
      internal: metrics
      external: 8080
      protocol: TCP
    labels: {}
    annotations: {}
  serviceMonitor:
    create: false
    name:
    scrapeInterval: 30s
    labels: {}
    annotations: {}
  pod:
    labels: {}
    annotations: {}

envs:
  clusterAssetGroup:
    relistInterval: 
  assetGroup:
    relistInterval: 
  clusterBucket:
    relistInterval: 
    maxConcurrentReconciles:
    region:
  bucket:
    relistInterval: 
    maxConcurrentReconciles:
    region:
  clusterAsset:
    relistInterval: 
    maxConcurrentReconciles:
  asset:
    relistInterval: 
    maxConcurrentReconciles:
  store:
    endpoint: 
    externalEndpoint:
    accessKey:
    secretKey:
    useSSL:
    uploadWorkers:
  loader:
    verifySSL:
    tempDir:
  webhooks:
    validation:
      timeout:
      workers:
    mutation:
      timeout:
      workers:
    metadata:
      timeout:
