# Default values for rafter-upload-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride:
fullnameOverride:

image:
  repository:
  tag:
  pullPolicy:

deployment:
  labels: {}
  annotations: {}
  replicas: 1
  extraProperties: {}

pod:
  labels: {}
  annotations: {}
  extraProperties: {}
  extraContainerProperties: {}

service:
  name:
  type: ClusterIP
  port:
    name: http
    internal: 3000
    external: 80
    protocol: TCP
  labels: {}
  annotations: {}

serviceAccount:
  create: true
  name:
  labels: {}
  annotations: {}

rbac:
  clusterScope:
    create: true
    role:
      name:
      labels: {}
      annotations: {}
      extraRules: []
    roleBinding:
      name:
      labels: {}
      annotations: {}

serviceMonitor:
  create: false
  name:
  scrapeInterval: 30s
  labels: {}
  annotations: {}

envs:
  host:
    value: "0.0.0.0"
  verbose: 
    value: "true"
  kubeconfigPath:
  upload:
    timeout:
      value: "30m"
    workers:
      value: "10"
    endpoint:
      value: 'dupa-minio.{{ .Release.Namespace }}.svc.cluster.local'
    externalEndpoint:
      value: 'http://localhost:9000'
    port:
      value: "9000"
    accessKey:
      valueFrom:
        secretKeyRef:
          name: '{{ include "rafterUploadService.fullname" . }}-minio'
          key: accesskey
    secretKey:
      valueFrom:
        secretKeyRef:
          name: '{{ include "rafterUploadService.fullname" . }}-minio'
          key: secretkey
    secure: 
      value: "false"
  bucket:
    privatePrefix:
      value: system-private
    publicPrefix:
      value: system-public
    region:
      value: "us-east-1"
  configMap:
    enabled:
      value: "true"
    name:
      value: "rafter-upload-service"
    namespace:
      value: "{{ .Release.Namespace }}"
