# Default values for rafter-upload-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride:
fullnameOverride:

minio:
  enabled: false

image:
  repository: rafter-upload-service
  tag: latest
  pullPolicy: Never

deployment:
  labels: {}
  annotations: {}
  replicas: 1
  extraProperties: {}

pod:
  labels: {}
  annotations: {}
    # sidecar.istio.io/inject: "false"
    # recreate: {{ .Release.Time.Seconds | quote }}
  extraProperties: {}
    # strategy:
    #   type: RollingUpdate
    #   rollingUpdate:
    #     maxUnavailable: 0
  extraContainerProperties: {}

service:
  name:
  type: ClusterIP
  port:
    name: http
    internal: 3000
    external: 80
    protocol: TCP
  labels: {}
  annotations: {}
    # auth.istio.io/80: NONE

serviceAccount:
  create: true
  name:
  labels: {}
  annotations: {}

rbac:
  clusterScope:
    create: true
    role:
      name:
      labels: {}
      annotations: {}
      extraRules: []
    roleBinding:
      name:
      labels: {}
      annotations: {}

serviceMonitor:
  create: false
  name:
  scrapeInterval: 30s
  labels: {}
  annotations: {}

envs:
  host:
    value: "0.0.0.0"
  verbose: 
    value: "true"
  kubeconfigPath:
  upload:
    timeout:
      value: "30m"
    workers:
      value: "10"
    endpoint:
      value: 'rafter-release-minio.{{ .Release.Namespace }}.svc.cluster.local'
    externalEndpoint:
    port:
      value: "9000"
    accessKey:
      valueFrom:
        secretKeyRef:
          name: 'rafter-release-minio'
          key: accesskey
    secretKey:
      valueFrom:
        secretKeyRef:
          name: 'rafter-release-minio'
          key: secretkey
    secure: 
      value: "false"
  bucket:
    privatePrefix:
      value: system-private
    publicPrefix:
      value: system-public
    region:
      value: "us-east-1"
  configMap:
    enabled:
      value: "true"
    name:
      value: "rafter-upload-service"
    namespace:
      value: "{{ .Release.Namespace }}"
