# Default values for rafter-upload-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride:
fullnameOverride:

image:
  repository:
  tag:
  pullPolicy:

deployment:
  labels: {}
  annotations: {}
  replicas: 1
  extraProperties: {}

pod:
  labels: {}
  annotations: {}
  extraProperties: {}
  extraContainerProperties: {}

service:
  name:
  type: ClusterIP
  port:
    name: http
    internal: 3000
    external: 80
    protocol: TCP
  labels: {}
  annotations: {}

serviceAccount:
  create: true
  name:
  labels: {}
  annotations: {}

rbac:
  clusterScope:
    create: true
    role:
      name:
      labels: {}
      annotations: {}
      extraRules: []
    roleBinding:
      name:
      labels: {}
      annotations: {}

serviceMonitor:
  create: false
  name:
  scrapeInterval: 30s
  labels: {}
  annotations: {}

envs:
  host:
  verbose:
  kubeconfigPath:
  upload:
    timeout:
    workers:
    endpoint:
    externalEndpoint:
    port:
    accessKey:
    secretKey:
    secure:
  bucket:
    privatePrefix:
    publicPrefix:
    region:
  configMap:
    enabled:
    name:
    namespace:
