apiVersion: v1
data:
  WEBHOOK_SERVICE_NAME: "serverless-webhook"
  WEBHOOK_SECRET_NAME: "serverless-webhook"
  WEBHOOK_PORT: "8443"

  WEBHOOK_VALIDATION_RESERVED_ENVS: "FUNC_RUNTIME,FUNC_HANDLER,FUNC_PORT,MOD_NAME,NODE_PATH,PYTHONPATH"

  WEBHOOK_VALIDATION_FUNCTION_REPLICAS_MIN_VALUE: "1"
  WEBHOOK_DEFAULTING_FUNCTION_REPLICAS_DEFAULT_PRESET: "s"
  WEBHOOK_DEFAULTING_FUNCTION_REPLICAS_PRESETS_MAP: |-

    {
      "s": {
        "min": 1,
        "max": 1
      },
      "m": {
        "min": 1,
        "max": 2
      },
      "l": {
        "min": 1,
        "max": 5
      }
    }

  WEBHOOK_VALIDATION_FUNCTION_RESOURCES_MIN_REQUEST_CPU: "10m"
  WEBHOOK_VALIDATION_FUNCTION_RESOURCES_MIN_REQUEST_MEMORY: "16Mi"
  WEBHOOK_DEFAULTING_FUNCTION_RESOURCES_DEFAULT_PRESET: "m"
  WEBHOOK_DEFAULTING_FUNCTION_RESOURCES_PRESETS_MAP: |-

    {
      "xs": {
        "requestCpu": "10m",
        "requestMemory": "16Mi",
        "limitsCpu": "25m",
        "limitsMemory": "32Mi"
      },
      "s": {
        "requestCpu": "25m",
        "requestMemory": "32Mi",
        "limitsCpu": "50m",
        "limitsMemory": "64Mi"
      },
      "m": {
        "requestCpu": "50m",
        "requestMemory": "64Mi",
        "limitsCpu": "100m",
        "limitsMemory": "128Mi"
      },
      "l": {
        "requestCpu": "100m",
        "requestMemory": "128Mi",
        "limitsCpu": "200m",
        "limitsMemory": "256Mi"
      },
      "xl": {
        "requestCpu": "200m",
        "requestMemory": "256Mi",
        "limitsCpu": "400m",
        "limitsMemory": "512Mi"
      }
    }

  WEBHOOK_VALIDATION_BUILD_JOB_RESOURCES_MIN_REQUEST_CPU: "200m"
  WEBHOOK_VALIDATION_BUILD_JOB_RESOURCES_MIN_REQUEST_MEMORY: "200Mi"
  WEBHOOK_DEFAULTING_BUILD_JOB_RESOURCES_DEFAULT_PRESET: "normal"
  WEBHOOK_DEFAULTING_BUILD_JOB_RESOURCES_PRESETS_MAP: |-

    {
      "slow": {
        "requestCpu": "200m",
        "requestMemory": "200Mi",
        "limitsCpu": "700m",
        "limitsMemory": "700Mi"
      },
      "normal": {
        "requestCpu": "700m",
        "requestMemory": "700Mi",
        "limitsCpu": "1100m",
        "limitsMemory": "1100Mi"
      },
      "fast": {
        "requestCpu": "1100m",
        "requestMemory": "1100Mi",
        "limitsCpu": "1700m",
        "limitsMemory": "1700Mi"
      }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"WEBHOOK_DEFAULTING_BUILD_JOB_DEFAULT_PRESET":"normal","WEBHOOK_DEFAULTING_BUILD_JOB_PRESETS_MAP":"\n{\n  \"slow\": {\n    \"requestCpu\": \"200m\",\n    \"requestMemory\": \"200Mi\",\n    \"limitsCpu\": \"700m\",\n    \"limitsMemory\": \"700Mi\"\n  },\n  \"normal\": {\n    \"requestCpu\": \"700m\",\n    \"requestMemory\": \"700Mi\",\n    \"limitsCpu\": \"1100m\",\n    \"limitsMemory\": \"1100Mi\"\n  },\n  \"fast\": {\n    \"requestCpu\": \"1100m\",\n    \"requestMemory\": \"1100Mi\",\n    \"limitsCpu\": \"1700m\",\n    \"limitsMemory\": \"1700Mi\"\n  }\n}","WEBHOOK_DEFAULTING_FUNCTION_DEFAULT_PRESET":"m","WEBHOOK_DEFAULTING_FUNCTION_PRESETS_MAP":"\n{\n  \"xs\": {\n    \"requestCpu\": \"10m\",\n    \"requestMemory\": \"16Mi\",\n    \"limitsCpu\": \"25m\",\n    \"limitsMemory\": \"32Mi\"\n  },\n  \"s\": {\n  \"requestCpu\": \"25m\",\n    \"requestMemory\": \"32Mi\",\n    \"limitsCpu\": \"50m\",\n    \"limitsMemory\": \"64Mi\"\n  },\n  \"m\": {\n    \"requestCpu\": \"50m\",\n    \"requestMemory\": \"64Mi\",\n    \"limitsCpu\": \"100m\",\n    \"limitsMemory\": \"128Mi\"\n  },\n  \"l\": {\n    \"requestCpu\": \"100m\",\n    \"requestMemory\": \"128Mi\",\n    \"limitsCpu\": \"200m\",\n    \"limitsMemory\": \"256Mi\"\n  },\n  \"xl\": {\n    \"requestCpu\": \"200m\",\n    \"requestMemory\": \"256Mi\",\n    \"limitsCpu\": \"400m\",\n    \"limitsMemory\": \"512Mi\"\n  }\n}","WEBHOOK_DEFAULTING_MAXREPLICAS":"1","WEBHOOK_DEFAULTING_MINREPLICAS":"1","WEBHOOK_PORT":"8443","WEBHOOK_SECRET_NAME":"serverless-webhook","WEBHOOK_SERVICE_NAME":"serverless-webhook","WEBHOOK_VALIDATION_BUILD_JOB_MIN_REQUEST_CPU":"200m","WEBHOOK_VALIDATION_BUILD_JOB_MIN_REQUEST_MEMORY":"200Mi","WEBHOOK_VALIDATION_FUNCTION_MIN_REQUEST_CPU":"10m","WEBHOOK_VALIDATION_FUNCTION_MIN_REQUEST_MEMORY":"16Mi","WEBHOOK_VALIDATION_MIN_REPLICAS_VALUE":"1","WEBHOOK_VALIDATION_RESERVED_ENVS":"FUNC_RUNTIME,FUNC_HANDLER,FUNC_PORT,MOD_NAME,NODE_PATH,PYTHONPATH"},"kind":"ConfigMap","metadata":{"annotations":{"meta.helm.sh/release-name":"serverless","meta.helm.sh/release-namespace":"kyma-system"},"creationTimestamp":"2020-09-14T09:30:07Z","labels":{"app":"serverless-webhook","app.kubernetes.io/instance":"serverless","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"serverless-webhook","role":"webhook"},"name":"serverless-webhook-envs","namespace":"kyma-system"}}
    meta.helm.sh/release-name: serverless
    meta.helm.sh/release-namespace: kyma-system
  labels:
    app: serverless-webhook
    app.kubernetes.io/instance: serverless
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: serverless-webhook
    role: webhook
  name: serverless-webhook-envs
  namespace: kyma-system
