---
# Source: serverless/charts/webhook/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: serverless-webhook
  namespace: default
  labels:
    app: 'serverless-webhook'
    app.kubernetes.io/instance: 'RELEASE-NAME'
    app.kubernetes.io/managed-by: 'Helm'
    app.kubernetes.io/name: 'serverless-webhook'
    role: webhook
