---
# Source: serverless/charts/webhook/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: serverless-webhook
  namespace: default
  labels:
    app: 'serverless-webhook'
    app.kubernetes.io/instance: 'RELEASE-NAME'
    app.kubernetes.io/managed-by: 'Helm'
    app.kubernetes.io/name: 'serverless-webhook'
    role: webhook
spec:
  ports:
    - name: http-metrics
      port: 9090
      targetPort: 9090
    - name: http-profiling
      port: 8008
      targetPort: 8008
    - name: https-webhook
      port: 443
      targetPort: 8443
  selector:
    app: serverless-webhook
    app.kubernetes.io/name: serverless-webhook
    app.kubernetes.io/instance: "RELEASE-NAME"
    role: webhook
